apiVersion: v2
name: wordpress-umbrella
description: A Helm chart for Kubernetes to deploy WordPress with MySQL
version: 0.1.0
dependencies:
  - name: mysql
    version: 0.1.0
    repository: "file://./charts/mysql"
   #condition: mysql.enabled
  - name: wordpress
    version: 0.1.0
    repository: "file://./charts/wordpress"
   #condition: wordpress.enabled
