apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.wordpress.name }}
  labels:
    app: {{ .Values.wordpress.labels.app }}
spec:
  ports:
    - port: {{ .Values.wordpress.service.port }}
  selector:
    app: {{ .Values.wordpress.labels.app }}
    tier: {{ .Values.wordpress.labels.tier }}
  type: {{ .Values.wordpress.service.type }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.wordpress.volume.claimName }}
  labels:
    app: {{ .Values.wordpress.labels.app }}
spec:
  accessModes: {{ .Values.wordpress.volume.accessModes }}
  resources:
    requests:
      storage: {{ .Values.wordpress.volume.storage }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.wordpress.name }}
  labels:
    app: {{ .Values.wordpress.labels.app }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.wordpress.labels.app }}
      tier: {{ .Values.wordpress.labels.tier }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.wordpress.labels.app }}
        tier: {{ .Values.wordpress.labels.tier }}
    spec:
      containers:
      - image: {{ .Values.wordpress.image }}
        name: {{ .Values.wordpress.name }}
        env:
        - name: WORDPRESS_DB_HOST
          value: {{ .Values.wordpress.env.dbHost }}
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.wordpress.env.dbPasswordSecret.name }}
              key: {{ .Values.wordpress.env.dbPasswordSecret.key }}
        - name: WORDPRESS_DB_USER
          value: {{ .Values.wordpress.env.dbUser }}
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: {{ .Values.wordpress.volume.claimName }}
